{
 "title": "Ccminer Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "2m",
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "SHOW TAG VALUES FROM \"summary\" WITH KEY = \"host\""
   },
   {
    "name": "instance",
    "query": "SHOW TAG VALUES FROM \"summary\" WITH KEY = \"instance\"   WHERE host =~ /$host/"
   },
   {
    "name": "gpu",
    "query": "SHOW TAG VALUES FROM \"threads\" WITH KEY = \"type_instance\"   WHERE host =~ /$host/ and instance=~ /$instance/"
   }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "summary",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "UPTIME" }
     ]
    }
   ]
  },
  {
   "title": "Miner name",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "summary",
     "select": [
      [
       { "params": [ "text" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "NAME" }
     ]
    }
   ]
  },
  {
   "title": "Miner version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "summary",
     "select": [
      [
       { "params": [ "text" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "VER" }
     ]
    }
   ]
  },
  {
   "title": "Algo",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "pool",
     "select": [
      [
       { "params": [ "text" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ALGO" }
     ]
    }
   ]
  },
  {
   "title": "Pool",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pool",
     "select": [
      [
       { "params": [ "text" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "POOL" }
     ]
    }
   ]
  },
  {
   "title": "GPU-s",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "summary",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "GPUS" }
     ]
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 4 },
   "format": "KHs",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "summary",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KHS" }
     ]
    }
   ]
  },
  {
   "title": "Power SUM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 4 },
   "format": "mwatt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "summary",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "POWERSUM" }
     ]
    }
   ]
  },
  {
   "title": "Effiency",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "powersum",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "summary",
     "query": "SELECT last(\"value\") FROM \"summary\" WHERE (\"host\" =~ /^$host$/ AND \"instance\" =~ /^$instance$/ AND \"type\" = 'POWERSUM') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "POWERSUM" }
     ]
    },
    {
     "alias": "hashrate",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" }
     ],
     "measurement": "summary",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KHS" }
     ]
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 11, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pool",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "ACC" }
     ]
    }
   ]
  },
  {
   "title": "Rejected",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 13, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "pool",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "REJ" }
     ]
    }
   ]
  },
  {
   "title": "User",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 9, "x": 15, "y": 4 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "pool",
     "select": [
      [
       { "params": [ "text" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "USER" }
     ]
    }
   ]
  },
  {
   "title": "Hashrate Sum",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "KHs" }
   ],
   "targets": [
    {
     "alias": "SUM",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "summary",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KHS" }
     ]
    }
   ]
  },
  {
   "title": "Power Sum",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 7 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "alias": "SUM",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "summary",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "POWERSUM" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 6, "w": 4, "x": 10, "y": 7 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "alias": "GPU $tag_type_instance",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "POWER" }
     ]
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 14, "y": 7 },
   "yaxes": [
    { "format": "KHs" }
   ],
   "targets": [
    {
     "alias": "GPU $tag_type_instance",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "GPU" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KHS" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 7 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "GPU $tag_type_instance",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "type_instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "TEMP" }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "gpu" },
  {
   "title": "GPU name",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "threads",
     "select": [
      [
       { "params": [ "text" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CARD" }
     ]
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "KHs" }
   ],
   "targets": [
    {
     "alias": ".",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KHS" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "alias": ".",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "POWER" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": ".",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "TEMP" }
     ]
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": ".",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FAN" }
     ]
    }
   ]
  },
  {
   "title": "Effiency",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "powersum",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "query": "SELECT last(\"value\") FROM \"summary\" WHERE (\"host\" =~ /^$host$/ AND \"instance\" =~ /^$instance$/ AND \"type\" = 'POWERSUM') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "POWER" }
     ]
    },
    {
     "alias": "hashrate",
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KHS" }
     ]
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 14 },
   "format": "KHs",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KHS" }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 } },
  {
   "title": "GPU name",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "threads",
     "select": [
      [
       { "params": [ "text" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CARD" }
     ]
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 20 },
   "yaxes": [
    { "format": "KHs" }
   ],
   "targets": [
    {
     "alias": ".",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KHS" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "alias": ".",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "POWER" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": ".",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "TEMP" }
     ]
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": ".",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FAN" }
     ]
    }
   ]
  },
  {
   "title": "Effiency",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 20 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "powersum",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "query": "SELECT last(\"value\") FROM \"summary\" WHERE (\"host\" =~ /^$host$/ AND \"instance\" =~ /^$instance$/ AND \"type\" = 'POWERSUM') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "POWER" }
     ]
    },
    {
     "alias": "hashrate",
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KHS" }
     ]
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 20 },
   "format": "KHs",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KHS" }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "GPU name",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 26 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "threads",
     "select": [
      [
       { "params": [ "text" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CARD" }
     ]
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 26 },
   "yaxes": [
    { "format": "KHs" }
   ],
   "targets": [
    {
     "alias": ".",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KHS" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "alias": ".",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "POWER" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": ".",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "TEMP" }
     ]
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": ".",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FAN" }
     ]
    }
   ]
  },
  {
   "title": "Effiency",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 26 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "powersum",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "query": "SELECT last(\"value\") FROM \"summary\" WHERE (\"host\" =~ /^$host$/ AND \"instance\" =~ /^$instance$/ AND \"type\" = 'POWERSUM') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "POWER" }
     ]
    },
    {
     "alias": "hashrate",
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KHS" }
     ]
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 26 },
   "format": "KHs",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KHS" }
     ]
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "GPU name",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "measurement": "threads",
     "select": [
      [
       { "params": [ "text" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "CARD" }
     ]
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 32 },
   "yaxes": [
    { "format": "KHs" }
   ],
   "targets": [
    {
     "alias": ".",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KHS" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" }
     ]
    }
   ]
  },
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 32 },
   "yaxes": [
    { "format": "mwatt" }
   ],
   "targets": [
    {
     "alias": ".",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "POWER" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": ".",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "TEMP" }
     ]
    }
   ]
  },
  {
   "title": "Fan Speed",
   "type": "graph",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 32 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": ".",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "FAN" }
     ]
    }
   ]
  },
  {
   "title": "Effiency",
   "type": "blackmirror1-singlestat-math-panel",
   "gridPos": { "h": 5, "w": 2, "x": 20, "y": 32 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "alias": "powersum",
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "query": "SELECT last(\"value\") FROM \"summary\" WHERE (\"host\" =~ /^$host$/ AND \"instance\" =~ /^$instance$/ AND \"type\" = 'POWERSUM') AND $timeFilter GROUP BY time($interval)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "POWER" }
     ]
    },
    {
     "alias": "hashrate",
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KHS" }
     ]
    }
   ]
  },
  {
   "title": "Hashrate",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 22, "y": 32 },
   "format": "KHs",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "2m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "threads",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=~", "value": "/^$host$/" },
      { "condition": "AND", "key": "instance", "operator": "=~", "value": "/^$instance$/" },
      { "condition": "AND", "key": "type_instance", "operator": "=~", "value": "/^$gpu$/" },
      { "condition": "AND", "key": "type", "operator": "=", "value": "KHS" }
     ]
    }
   ]
  }
 ]
}